In [1]:
#task 01
#Write a NumPy program to create an array of all even integers from 30 to 70
#using import of numpy
import numpy as np 

In [2]:
#Creating an array of even integers 

even_array= np.arange (30,71,2) # np.arange - here generate an array starting from 30 to 70 with a step of 2


In [3]:
#printing the result
print ("Array f even inetegers fron 30 to 70:")
print(even_array)

Array f even inetegers fron 30 to 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [4]:
#task 02 
#Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.
# using import 
import numpy as np 

In [5]:
#generating an array of 15 randon numbers 
random_array = np.random.randn(15)

In [6]:
print ("Array of 15 random numbers from standard normal distribution : " )
print (random_array)

Array of 15 random numbers from standard normal distribution : 
[-0.34713381 -0.88288981 -0.13481945  1.38006309 -0.01506124 -0.41859339
  0.94804435  0.58473993  0.80298419  0.38358222  1.11094296  1.03907043
  0.96535314  1.23463669  0.53256327]


In [7]:
#task 03 
#How to compute the cross-product of two matrices in NumPy?
# first using import 
import numpy as np 

In [8]:
#defining two matrices
matrix1 = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

#defining 2nd matrix
matrix2 = np.array ([[9,8,7],
                     [6,5,4],
                     [3,2,1]])


In [9]:
#Now computing the cross product of the two matrices
cross_product = np.cross (matrix1, matrix2)



In [10]:
#printing the result 
print ("Cross-product of the two matrices:")
print (cross_product)

Cross-product of the two matrices:
[[-10  20 -10]
 [-10  20 -10]
 [-10  20 -10]]


In [11]:
#task04
#How to compute the determinant of an array using NumPy?
#using import of numpy
import numpy as np



In [12]:
#defining a square matrix for which we want to compute determinant
matrix = np.array([[1,2],
                   [3,4]])

In [13]:
#Computing the determinant of the matrix
determinant_value = np.linalg.det(matrix) # here np.linalg.det is used to calculate the determinant of the specified matrix 

In [14]:
#printing the result
print ("Determinant of the matrix :")
print (determinant_value)

Determinant of the matrix :
-2.0000000000000004


In [15]:
#task 05
#How to create a 3x3x3 array with random values using NumPy?
#imporitn numpy
import numpy as np


In [16]:
#creating a 3x3x3 array with random values between 0 and 1
random_3d_array = np.random.rand (3,3,3) #here np.random.rand generates a 3-dimensional array .


In [17]:
#printing the result
print ("3x3x3 array with random values :")
print (random_3d_array)

3x3x3 array with random values :
[[[0.34403157 0.39473111 0.26759644]
  [0.05448884 0.7835846  0.81069672]
  [0.05098024 0.84431485 0.21888705]]

 [[0.5888115  0.0353523  0.15952758]
  [0.66428004 0.08292472 0.81076791]
  [0.1446571  0.71751936 0.3461673 ]]

 [[0.47668172 0.26999456 0.59661161]
  [0.79966023 0.41302432 0.38937151]
  [0.54002457 0.82383708 0.87699553]]]


In [18]:
#task 06
#How to create a 5x5 array with random values and find the minimum and maximum values using NumPy?
#importing numpy 
import numpy as np 


In [19]:
#Creating a 5x5 array with random values betwwen 0 and 1 
random_5x5_array = np.random.rand(5,5)

In [20]:
#printing the result 
print ("5x5 array with random value :")

print ( random_5x5_array)

5x5 array with random value :
[[0.01585744 0.27332387 0.40642938 0.129403   0.84626047]
 [0.84916487 0.41243673 0.24911267 0.17962931 0.10755018]
 [0.9446868  0.96972089 0.8004717  0.30347193 0.26791881]
 [0.03702671 0.14235099 0.5745128  0.18816437 0.09009996]
 [0.03184909 0.34507687 0.74879591 0.01342841 0.82541641]]


In [21]:
# but if we also want to know the min and max values in these array so we will do :
min_value = np.min(random_5x5_array)
max_value = np.max(random_5x5_array)


In [22]:
#printing the result og min and max values 
print ("Minimum value:" , min_value)
print ("Maximum value:" , max_value)

Minimum value: 0.01342840635239373
Maximum value: 0.9697208862909509


In [23]:
#task 07 
#How to compute the mean, standard deviation, and variance of a given array along the second axis in NumPy?
#importing numpy
import numpy as np



In [24]:
#Now creating a sample 2d array 
array_2d = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])


In [25]:
#Now computing the mean along the second axis i.e : axis =1 
mean_values = np.mean(array_2d, axis =1)

In [26]:
# computing the standard devation along the second axis 
std_dev_values = np.std(array_2d, axis=1)

In [27]:
#Now computing the varience along the second axis 
varience_values = np.var(array_2d, axis=1)


In [28]:
# now print the value of each 
print ("Mean value along the second axis :")
print (mean_values)

Mean value along the second axis :
[2. 5. 8.]


In [29]:
print ("Standard deviation along the second axis :")
print (std_dev_values)

Standard deviation along the second axis :
[0.81649658 0.81649658 0.81649658]


In [30]:
print ("Varience value along the second axis :")
print (varience_values)

Varience value along the second axis :
[0.66666667 0.66666667 0.66666667]


In [31]:
    ######################################## THAT'S IT ]#############################################